### ISSUE TITLE
Discussion: vanilla is ok

### ISSUE THREAD

**Issue by donovanr** [AllenCellModeling/pytorch_integrated_cell#79]
## Issue summary
don't be ashamed

## Details
> You all seem a little abashed that this is a “plain vanilla” beta-VAE and not some kind of breakthrough in the ML space. This is FINE! It is almost always better to use the simplest possible alternative. The merit of this paper is the cell biological application, and the way that the beta-VAE makes it possible to put quantitative values (and probabilities of specific observations) on things that are very hard to describe in anything other than qualitative terms. We are aiming for a computational biology audience, not a CS/ML audience.

## TODO
- [x] manuscript text

**Comment by tknijnen** [comment]
Indeed. This issue can be closed as it does not have any action items it seems.

**Comment by donovanr** [comment]
the action item is to change the manuscript text to highlight this as a feature.

**Comment by donovanr** [comment]
@gregj adding you since this seems pretty decoupled from other stuff.  I'd say a paragraph citing some lit about how reliable VAEs are compared to GANs, the multi-task benefits, etc would do it.  Maybe citing success of vanilla architecture in other areas from say general stuff like faces to other areas of comp bio like scvi?
